config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'teams#show'

  #
  # Authentication / Authorization
  #
  devise_for :users


  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

  #
  # API
  #
  namespace :api do
    namespace :v1 do
      resources :events, only: %i[index]
    end
  end

  #
  # Application
  #
  scope '/:locale' do
    resources :teams do
      resources :calendars, shallow: true
    end

    resources :events do
      resources :comments, module: :events
    end

    resources :comments do
      resources :comments, module: :comments
    end

    resources :organizations, only: %i[create]
    resources :share_links, only: %i[create]

    get '/calendars/shared/:token', to: 'share_links#authorize_request', constraints: { token: /[^\/]+/ }
  end

  post '/search', to: 'search#search'
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: 'Comment'
  has_many :comments, foreign_key: :parent_id, dependent: :destroy

  has_rich_text :body

  validates :body, presence: true

  self.implicit_order_column = 'created_at'

  after_create_commit do
    broadcast_append_to [commentable, :comments], target: "#{dom_id(parent || commentable)}_comments", partial: 'comments/comment_with_replies'
  end

  after_update_commit do
    broadcast_replace_to self
  end

  after_destroy_commit do
    broadcast_remove_to self
    broadcast_action_to self, action: :remove, target: "#{dom_id(self)}_with_comments"
  end

  # def self.recursive_find(id)
  #   sql = <<-SQL.squish
  #     WITH RECURSIVE comment_tree_cte
  #     AS (
  #       SELECT id, parent_id, commentable_id, user_id, created_at
  #       FROM comments
  #       WHERE commentable_id = :id
  #       UNION
  #         SELECT comments.id, comments.parent_id, comments.commentable_id, comments.user_id, comments.created_at
  #         FROM comments
  #       JOIN comment_tree_cte ON comments.parent_id = comment_tree_cte.id
  #     )
  #     SELECT * FROM comment_tree_cte;
  #   SQL

  #   records = find_by_sql([sql, id: id])
  #   ActiveRecord::Associations::Preloader.new.preload(records, [:rich_text_body, :user])
  #   records
  # end
end

app/controllers/comments/comments_controller.rb
class Comments::CommentsController < ApplicationController
  include Commentable

  before_action :set_commentable

  private

    def set_commentable
      @parent = Comment.find(params[:comment_id])
      @commentable = @parent.commentable
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment

  def show

  end

  def edit

  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @comment.commentable }
    end
  end

  private

    def set_comment
      @comment = authorize current_user.comments.includes(:comments).find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/events/comments_controller.rb
class Events::CommentsController < ApplicationController
  include Commentable

  before_action :set_commentable

  private

    def set_commentable
      @commentable = Event.find(params[:event_id])
    end
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from comment %>

<%= turbo_frame_tag comment do %>
  <div class="d-flex justify-content-between pt-2">
    <div>
      <%= image_tag comment.user.gravatar_url, class: 'gravatar mb-2 me-2' %>
      <%= comment.user.pseudonym || comment.user.email %>
      ·
      <small class="text-muted"><%= time_ago_in_words(comment.created_at) %> ago</small>
    </div>
    <div class="d-flex">
      <%= link_to 'Edit', edit_comment_path(comment), class: 'me-2' %>
      <%= button_to 'Delete', comment_path(comment), method: :delete, data: { confirm: t('comment.delete_confirmation') } %>
    </div>
  </div>

  <%= comment.body %>
<% end %>

app/views/comments/_comment_with_replies.html.erb
<%= turbo_stream_from comment, :comments %>

<div class="ps-3 border-start" id="<%= dom_id(comment) %>_with_comments" data-controller="comment-reply">
  <%= render comment %>

  <div class='small pb-1'>
    <%= link_to 'Reply', '#', data: { action: 'click->comment-reply#toggle' } %>
  </div>

  <div id="<%= dom_id(comment) %>_comments">
    <%= render partial: 'comments/form', locals: { commentable: comment, comment: Comment.new, data: { comment_reply_target: 'form' }, class: 'd-none' } %>
    <%= render partial: 'comments/comment_with_replies', collection: comment.comments, as: :comment %>
  </div>
</div>

app/views/comments/_form.html.erb
<% model = [local_assigns[:commentable], comment].compact %>

<%= form_with model: model,
              id:    dom_id_for_records(*model),
              data:  local_assigns[:data],
              class: ['my-4'] + Array.wrap(local_assigns[:class]) do |form| %>

  <% if form.object.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <%= form.rich_text_area :body, id: "#{dom_id_for_records(*model)}_body" %>

  <div class="d-flex justify-content-between">
    <span><%= link_to t('cancel'), comment, class: 'btn btn-sm btn-info' if form.object.persisted? %></span>
    <span><%= form.submit class: 'btn btn-sm btn-primary' %></span>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render 'comments/form', comment: @comment %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>