config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'teams#show'

  #
  # Authentication / Authorization
  #
  devise_for :users


  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

  #
  # API
  #
  namespace :api do
    namespace :v1 do
      resources :events, only: %i[index]
    end
  end

  #
  # Application
  #
  scope '/:locale' do
    resources :teams do
      resources :calendars, shallow: true
    end

    resources :events do
      resources :comments, module: :events
    end

    resources :comments do
      resources :comments, module: :comments
    end

    resources :organizations, only: %i[create]
    resources :share_links, only: %i[create]

    get '/calendars/shared/:token', to: 'share_links#authorize_request', constraints: { token: /[^\/]+/ }
  end

  post '/search', to: 'search#search'
end

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom bg-secondary d-flex justify-content-center align-items-center">
  Made with 🖤

  <span class='mx-3'>·</span>

  <%= link_to 'https://gitlab.com/kawsay/open_calendar' do %>
    <%= image_tag 'gitlab.svg', size: '30x30' %>
  <% end %>

  <span class='mx-3'>·</span>

  <%= link_to 'https://github.com/Kawsay/open_calendar' do %>
    <%= image_tag 'github.svg', size: '25x25' %>
  <% end %>
</footer>

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-dark bg-dark mb-4 shadow'>
  <div class='container-fluid'>
    <%= active_link_to 'Caisse de Solidarité', root_path, class: 'navbar-brand me-5', endpoint: ['', '/', '/#', '/calendars'] %>

    <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbar-links' aria-controls='navbar-links' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbar-links'>
      <ul class='navbar-nav'>
        <% if user_signed_in? && !@teams.blank? %>
          <li class='nav-item dropdown'>
            <%= active_link_to @current_team.name, '#', class: 'nav-link dropdown-toggle', id: 'navbarDropdown', role: 'button', data: { bs_toggle: 'dropdown' }, aria: { expanded: false },  endpoint: ['', '/', '/#', '/teams/'] %>
            <ul class='dropdown-menu dropdown-menu-dark' aria-labelledby='navbarDropdown'>
              <% @teams.each do |team| %>
                <li><%= link_to team.name, team_path(team), class: 'dropdown-item' %></li>
              <% end %>
              <li><hr class='dropdown-divider'></li>
              <li><%= link_to t('team.create'), new_team_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
        <% elsif user_signed_in? %>
          <%= active_link_to t('team.create'), new_team_path, class: 'nav-link' %>
        <% end %>
      </ul>

      <div class='navbar-nav ms-auto'>
        <% if current_user&.admin? %>
          <%= active_link_to t('administration.administration'), root_path, class: 'nav-link me-2', endpoint: '/admin' %>
        <% end %>

        <% if user_signed_in? %>
          <div data-controller="layout--visibility" data-action="click@window->layout--visibility#hideIfOutsideClick">
            <%= form_with url: '/search', method: :post, class: 'me-2', data: { controller: 'forms--submission', 'forms--submission-target': 'form' } do |form| %>
              <%= form.text_field :query, class: 'form-control', placeholder: t('search.placeholder'), data: { action: 'input->forms--submission#submit' } %>
            <% end %>

            <div id="global-search-results" data-layout--visibility-target="hideable"></div>
          </div>
        <% end %>

        <%= login_or_disconnect_link class: 'nav-link mx-2', data: { turbo: false } %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaisseSo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="parameters" content="<%= { route: "#{controller_name}/#{action_name}", payload: (@payload || {}) }.to_json %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body class="vh-100">
    <%= render 'layouts/navbar' %>

    <div class='container-xxl'>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>